# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hfeeds < Formula
  desc "Hacker feeds CLI for GitHub Trending, Hacker News, Product Hunt, Reddit, and V2EX"
  homepage "https://github.com/bvgroup-co/hacker-feeds-go-cli"
  version "0.4.10"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/bvgroup-co/hacker-feeds-go-cli/releases/download/v0.4.10/hfeeds_0.4.10_darwin_amd64.tar.gz"
      sha256 "8056858014475ea32ff01d0b09ddfeea5432eee947dba6091ea80918608bf1fa"

      define_method(:install) do
        bin.install "hfeeds"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/bvgroup-co/hacker-feeds-go-cli/releases/download/v0.4.10/hfeeds_0.4.10_darwin_arm64.tar.gz"
      sha256 "05376eb6bd87d9c0083c4767891f56256d48584c379098bca3bd4c772fded6d4"

      define_method(:install) do
        bin.install "hfeeds"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/bvgroup-co/hacker-feeds-go-cli/releases/download/v0.4.10/hfeeds_0.4.10_linux_amd64.tar.gz"
      sha256 "4279d73ce5756de0e44756e74cc8c76d0a9f24ae6edcf2cf0256d610c0ea68e3"
      define_method(:install) do
        bin.install "hfeeds"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bvgroup-co/hacker-feeds-go-cli/releases/download/v0.4.10/hfeeds_0.4.10_linux_arm64.tar.gz"
      sha256 "9505882af21a394fa5c80562bd3f1cb575fdc914206393d10d058f291262dc40"
      define_method(:install) do
        bin.install "hfeeds"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/hfeeds --version")
    assert_match "hfeeds", shell_output("#{bin}/hfeeds --help")
  end
end
