# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hfeeds < Formula
  desc "Hacker feeds CLI for GitHub Trending, Hacker News, Product Hunt, Reddit, and V2EX"
  homepage "https://github.com/bvgroup-co/hacker-feeds-go-cli"
  version "0.4.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/bvgroup-co/hacker-feeds-go-cli/releases/download/v0.4.6/hfeeds_0.4.6_darwin_amd64.tar.gz"
      sha256 "c325f8b0b635f6d9982e022eba17202d3320357a5ff614c6955b877855be320a"

      define_method(:install) do
        bin.install "hfeeds"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/bvgroup-co/hacker-feeds-go-cli/releases/download/v0.4.6/hfeeds_0.4.6_darwin_arm64.tar.gz"
      sha256 "9953728dc0f7f5c7cf81707d44b19590146861427c1c7da6fffc887a01fe4a77"

      define_method(:install) do
        bin.install "hfeeds"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/bvgroup-co/hacker-feeds-go-cli/releases/download/v0.4.6/hfeeds_0.4.6_linux_amd64.tar.gz"
      sha256 "7459f32ee5cfbc385f9c8ff7ee34b0776fa02bcbb7eb6f774922d50ef38b40f7"
      define_method(:install) do
        bin.install "hfeeds"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bvgroup-co/hacker-feeds-go-cli/releases/download/v0.4.6/hfeeds_0.4.6_linux_arm64.tar.gz"
      sha256 "2a10644ccdac3ccdf45f653749f78a150147bdd84eb982414ccfda92f8658020"
      define_method(:install) do
        bin.install "hfeeds"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/hfeeds --version")
    assert_match "hfeeds", shell_output("#{bin}/hfeeds --help")
  end
end
